# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "my-first-app"
client_id = "adb202239180d733f4bfa2846cb3a76c"
application_url = "https://vii-processing-naturally-darwin.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vii-processing-naturally-darwin.trycloudflare.com/auth/callback",
  "https://vii-processing-naturally-darwin.trycloudflare.com/auth/shopify/callback",
  "https://vii-processing-naturally-darwin.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ashwe-tmg-demo.myshopify.com"
